// Auto-generated by CMake — do not edit manually.
#ifndef VERSION_GENERATED_H
#define VERSION_GENERATED_H

#define GIT_COMMIT_COUNT  "50"
#define GIT_SHORT_HASH    "2b5a2c6"
#define GEN2_VERSION      "1.0.50"
#define GEN2_VERSION_FULL "1.0.50-2b5a2c6"

#endif // VERSION_GENERATED_H
