// Auto-generated by CMake — do not edit manually.
#ifndef VERSION_GENERATED_H
#define VERSION_GENERATED_H

#define GIT_COMMIT_COUNT  "63"
#define GIT_SHORT_HASH    "768df6d"
#define GEN2_VERSION      "1.0.63"
#define GEN2_VERSION_FULL "1.0.63-768df6d"

#endif // VERSION_GENERATED_H
